directory: /mnt/storage/Music
library: /mnt/storage/Music/beets.blb

import:
    copy: no
    write: no

plugins: convert web usertag

convert:
    command: ffmpeg -i $source -y -vn -acodec libvorbis -aq 7 $dest
    extension: ogg
    dest: /mnt/storage/MusicPhone
    never_convert_lossy_files: yes
